### ISSUE TITLE
IntelliJ, and multiple files...

### ISSUE THREAD

**Issue by MrJoy** [Ashald/EnvFile#3] opened 2015-09-01 20:34 UTC
A bit of a two-fer, but could you add:
1. Support for multiple files with an explicit load order -- last-one-wins on key conflicts.
2. Ability to use this with IntelliJ and non-Python projects (in particular, for JVM-based projects of course).

Basically I have a scaffold of build tools using [dotenv](https://github.com/bkeepers/dotenv) and want to be able to make use of the relevant files from IntelliJ.

**Comment by Ashald** [comment] 2015-09-02 03:45
Hooray! First issue. :)

> Support for multiple files with an explicit load order -- last-one-wins on key conflicts.
There are no problems from technical point of view but I guess how to do UI for this... Do you have any ideas?

> Ability to use this with IntelliJ and non-Python projects (in particular, for JVM-based projects of course).
Due to IntelliJ IDEA architecture it's not possible to implement this as one-fro-all so I will need to add special code fore each platform. What will be priorities for you? IntelliJ IDEA itself?

**Comment by MrJoy** [comment] 2015-09-02 06:21
IntelliJ IDEA Community Edition is what we're using around here.  We specifically have Scala-based projects on JDK 1.6 and 1.8, built using Maven.  Not sure if any/all of that is relevant but including it just in case.

As for UI, I'd do a simple list view with options to move an item up/down the list.  It should be reasonably self-evident with little/no explanation that it runs through them first-to-last, and it's trivial to determine that semantic experimentally so likely little need to bog things down with exposition about it.

(Thank you for your responsiveness, BTW!)

**Comment by Ashald** [comment] 2015-09-03 16:25
That's very relevant, thanks. What type of build configuration are you using? Is it built-into IDEA? Or you using some kind of Scala plugin? If it's built into IDEA, is it CE or PE?

**Comment by MrJoy** [comment] 2015-09-03 17:27
It's a plugin -- one of the preferred ones it recommends when you set Idea up the first time, and we're using CE.

**Comment by ansel1** [comment] 2015-11-19 18:40
Would you be able to make this work with all runtime configuration types by moving support for .env files up to the project level?  In other works, configure the .env file (or list of files, love that idea) in the project settings, and use that to create an environment inherited by all runtime configurations?

**Comment by Ashald** [comment] 2015-11-19 21:46
Ansel, that's a nice idea. I will look into it. Thanks.

**Comment by EvertEt** [comment] 2016-08-08 09:40
Any chance this is coming to IDEA?

**Comment by ashald** [comment] 2016-08-10 04:32
@EvertEt would be helpful to hear desired use-case - how exactly would you like this one to be integrated? For what kind of run configurations?

**Comment by EvertEt** [comment] 2016-08-10 05:41
@Ashald Thank you for your reply! I would like to be able to load an .env file for a grails run configuration. (Now I have to fill in the env vars in IDEA itself or run it with dotenv).

**Comment by olslash** [comment] 2016-11-28 10:01
i'd also love to see this for intellij-- in any of the build/run configurations (no idea why they haven't brought this to the IDE on their own yet)

**Comment by ashald** [comment] 2016-11-30 14:29
Not sure that it'll be easy to add this to all build configurations but I'll see what I can do about it.

**Comment by refack** [comment] 2017-01-09 23:12
http://stackoverflow.com/questions/27093002/specifying-webstorm-environment-from-file

**Comment by ashald** [comment] 2017-01-10 05:47
Finally I was able to find a bit of time to look into this deeper. There are good news and bad news.

Good news are:
1) Yes, I'm working on it and it's coming
2) I'll try to roll out multiple files support together with multiple platforms support

Bad news are:
1) There are no truly generic way to add support for such functionality across all platforms
2) But there is semi-generic way to do that (if I'm not missing anything)
3) Although it probably will make the UI for the plugin a little bit less convenient
4) And it will take time to implement this new approach
4) Therefore probably platform support will be added one by one

Now, I will start from integrating with IDEA as it's the most requested platform. As for others - need to figure out order based on demand. Stay tuned. ;)

**Comment by refack** [comment] 2017-01-10 23:18
👍 WebStorm

**Comment by ashald** [comment] 2017-01-16 05:49
As it usually happens, there are good news and bad news.

Among the good news is that I think I made some progress on my research how to bring `EnvFile` functionality to more platforms (at least IDEA and RubyMine).

The bad news... It looks like IDEA platform is done in a way that there is no generic way to bring this functionality to all platforms, by design (or by a flaw in design). In long term I might try to talk to JetBrains to extend the plugin API and/or to include `EnvFile` functionality into the IDEA platform core. But that might take a lot of time.
Meanwhile, I'll try to integrate with as much platforms/languages as I can. Speaking of `WebStorm` - that's one of tricky cases. As far as I understand, `WebStorm` is not some _essentially_ special product but rather a basic IDEA distribution with number of bundled plugins, each of them developed in a different way (by potentially different people). This essentially mean that I cannot integrate with `WebStorm` as a whole - I'll have to integrate with `Node.js` plugin (and its run configurations), `Karma` plugin and its run configurations and so on...

Given the details I described above, for those who looking forward to using `EnvFile` plugin with currently unsupported IDEA-based products, I'd like to ask you to share a bit more info about your use-cases: not only the name of the platform but also list of run configuration types you use [and need `EnvFile` for].

**Comment by ashald** [comment] 2017-01-17 06:13
Version `2.0` is now available for downloads. Please check-out the `README.md` as it contains updated usage guide.

I'm closing this issue as `v2.0` implements support for multiple files and provides integration with IDEA and RubyMIne (lower hanging fruits)/ For other platforms - please **create new issues and specify not only platform** (e.g. `WebStorm`) **but also run configuration types** (e.g. `Node.js`) you would like to see supported.

**Closed by ashald** 2017-01-17 06:13 UTC
Labels: enhancement
