### ISSUE TITLE
Fails to install on on Ultimate edition of IDEA 2021.2 from July 27, 2021 build

### ISSUE THREAD

**Issue by IgorNetOp** [Ashald/EnvFile#153] opened 2021-08-18 12:12 UTC
![image](https://user-images.githubusercontent.com/49119182/129895883-2c2015f6-142e-4764-a349-4239fd379901.png)

**Comment by msvidal2** [comment] 2021-08-18 14:30
.

**Comment by ghost** [comment] 2021-08-18 14:32
[146](https://github.com/ashald/EnvFile/issues/146)

**Comment by ineph** [comment] 2021-08-18 15:05
#151
Easy solution that work for me (note that is not an ideal solution as he says):
 _Originally posted by @Doug-Cleo in https://github.com/ashald/EnvFile/issues/151#issuecomment-898447980_

**Comment by ashald** [comment] 2021-09-02 05:03
Closing as duplicate of #151

**Closed as completed by ashald** 2021-09-02 05:03 UTC
