### ISSUE TITLE
EnvFile plugin not working on 2021.2

### ISSUE THREAD

**Issue by ambroziepaval** [Ashald/EnvFile#146] opened 2021-08-02 06:56 UTC
EnvFile plugin not working with version 2021.2 (Ultimate Edition).
Build #IU-212.4746.92, built on July 27, 2021

Message:
Plugin "EnvFile" was not installed: Failed to load the plugin descriptor from the downloaded archive. The archive is probably not an IntelliJ plugin.

**Comment by vikingair** [comment] 2021-08-02 09:15
Duplicate of #140

**Comment by sajjadtalebi** [comment] 2021-08-07 14:24
> EnvFile plugin not working with version 2021.2 (Ultimate Edition).
> Build #IU-212.4746.92, built on July 27, 2021
> 
> Message:
> Plugin "EnvFile" was not installed: Failed to load the plugin descriptor from the downloaded archive. The archive is probably not an IntelliJ plugin.

I had a similar problem with this plugin. Until this issue is resolved in the new version, you can copy the contents of your env file instead of using this plugin and paste it through the Edit Configuration in the Environment Variables section. I did this and my problem was solved.

**Comment by vikingair** [comment] 2021-08-09 07:05
@sajjadtalebi This would require tedious manual work as the configuration is injected in many places in our project.

I've chosen to use "Jetbrains Toolbox" to downgrade my IDE to 2021.1.3 until this issue gets resolved. Hopefully soon :v:

**Comment by vojkny** [comment] 2021-08-12 14:24
<img width="394" alt="Screenshot 2021-08-12 at 16 22 44" src="https://user-images.githubusercontent.com/401107/129213994-8c453486-6a43-4fd1-beba-2d75f95eaf10.png">

**Comment by BorzdeG** [comment] 2021-08-12 14:39
@knyttl see #140 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/2332528/129216440-fa8fab39-d44f-4e91-b6ac-643efc6b7ce8.png">

**Comment by vojkny** [comment] 2021-08-12 17:14
@BorzdeG thanks!

https://github.com/eltonsandre/EnvFile/releases/tag/v3.2.2

**Comment by draeron** [comment] 2021-08-12 19:14
seems like the plugin  only works for IntelliJ, on Goland 2021.2 i get an error message.

![image](https://user-images.githubusercontent.com/2256246/129255076-db2dcbf2-23a2-4661-ba21-4245740b3901.png)

**Comment by arigesher** [comment] 2021-08-13 05:16
> seems like the plugin only works for IntelliJ, on Goland 2021.2 i get an error message.
> 
> ![image](https://user-images.githubusercontent.com/2256246/129255076-db2dcbf2-23a2-4661-ba21-4245740b3901.png)

Can confirm the identical error in PyCharm.

**Comment by BorzdeG** [comment] 2021-08-13 05:21
@draeron , @arigesher install https://plugins.jetbrains.com/plugin/11594-properties

**Comment by BorzdeG** [comment] 2021-08-13 05:23
But I don't understand why it requires a `com.intellij.java` plugin in GoLand ... 

 ![image](https://user-images.githubusercontent.com/2332528/129308722-4a4d1c31-9dbf-4f58-96f2-0bf3c048c16d.png)

**Comment by ashald** [comment] 2021-09-02 05:22
Closing as a duplicate, also - fixed.

**Closed as completed by ashald** 2021-09-02 05:22 UTC

**Comment by dino-powerflex** [comment] 2022-01-06 00:20
PyCharm 2021.2.4 (Professional Edition)
Build #PY-212.5712.39 built on December 20, 2021

EnvFile 3.2.2 

Does not load env file. I have to manually copy contents of env file to 'Environment variables' for each test configuration.

Is there any plan to fix this for PyCharm 2021.2.x?
