### ISSUE TITLE
Failed to load the plugin descriptor from the downloaded archive

### ISSUE THREAD

**Issue by Whitefield87** [Ashald/EnvFile#151] opened 2021-08-13 10:23 UTC
I receive this error when trying to install this plugin to pycharm 2021.2

**Comment by penkin** [comment] 2021-08-13 11:58
Having the same issue.

![Screenshot 2021-08-13 at 13 58 06](https://user-images.githubusercontent.com/771661/129353834-c2dbeff9-908c-4766-bb7d-291ed2a58dae.png)

**Comment by Doug-Cleo** [comment] 2021-08-13 13:11
I'm also having the same problem. Got around it by installing this 
[EnvFile-3.2.2-SNAPSHOT.zip](https://github.com/ashald/EnvFile/files/6982603/EnvFile-3.2.2-SNAPSHOT.zip) manually, but that's not an ideal solution.

**Comment by penkin** [comment] 2021-08-13 13:17
Thanks @Doug-Cleo that works perfectly.

**Comment by anopheles** [comment] 2021-08-17 22:10
Duplicate of https://github.com/ashald/EnvFile/issues/140

**Comment by jhud** [comment] 2021-08-26 11:06
> I'm also having the same problem. Got around it by installing this
> [EnvFile-3.2.2-SNAPSHOT.zip](https://github.com/ashald/EnvFile/files/6982603/EnvFile-3.2.2-SNAPSHOT.zip) manually, but that's not an ideal solution.

@Doug-Cleo 's solution worked great, but here's some extra tips for installing:

- Note that Safari will automatically unzip the file for you, so use another browser instead, so you get the ZIP file.
- Press ⌘, to open IDE settings and select Plugins.
- On the Plugins page, click The Settings button and then click Install Plugin from Disk.
- Select the plugin archive file and click OK.
- Click OK to apply the changes and restart the IDE if prompted.

**Comment by ashald** [comment] 2021-09-02 05:04
Closing as duplicate of #140

**Closed as completed by ashald** 2021-09-02 05:04 UTC

**Comment by mklueh** [comment] 2023-08-19 07:13
This is still a thing, even with IntelliJ 2023.2
