### ISSUE TITLE
Django Console stopped reading environment variables

### ISSUE THREAD

**Issue by smcoll** [Ashald/EnvFile#7] opened 2015-11-19 21:33 UTC
i've been using the plugin successfully for some weeks.

Today, at some point, i couldn't use the Django Console because it was complaining about missing configurations (`SECRET_KEY`, for example) that should be available.

```
Traceback (most recent call last):
 [...]
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

The settings file selected for Django support reads the `SECRET_KEY` value from the environment (`'SECRET_KEY': os.environ.get('SECRET_KEY')`).

This had been working for months.  i don't know why it stopped all of the sudden.

i also have the env file selected in "Build, Execution, Deployment > Console > Django Console".  i tried unselecting "Read from file" and manually entereing the variables, but it still didn't work.

In "Languages & Frameworks > Django > Enable Django Support > Environment variables", i added the variables and it still didn't work.

The manage.py@Service worked just fine; it could find the variables (manually-entered only, i think), from "Languages & Frameworks > Django > Enable Django Support > Environment variables"

Uninstalling this plugin (and restarting PyCharm) immediately fixed the issue, in that the manually entered env variables were being applied in the Django Console.

Interestingly, after reinstalling the pluging and restarting, it was still working, and then after selecting the env file again, it was back to working as normal.

PyCharm 5.0.1

**Comment by Ashald** [comment] 2015-11-19 21:45
I will try to reproduce it and will be in a contact, stay tuned. ;)

**Comment by smcoll** [comment] 2015-12-11 20:48
@Ashald is the "Languages & Frameworks > Django" implementation supposed to have it's own "Read from file" selection (i don't see a selector there), or is it borrowing from the "Console > Django Console" values?

**Comment by Ashald** [comment] 2016-04-14 20:47
Ooops, was out of the loop for a while.

I think believe current implementation only integrates with run configuration window...

Hope to do a release with bugfixes within next month - will try to get to this issue as well.

**Comment by smcoll** [comment] 2016-04-14 21:59
@Ashald that would be welcome.  i miss using the plugin.

**Comment by cancan101** [comment] 2016-07-21 13:58
For some visual clarification, there are two locations to configure Django. Only one of them is used for the run commands and that one does not currently use the env file:

![image](https://cloud.githubusercontent.com/assets/51059/17025358/70420c0e-4f29-11e6-9caa-65a1e992dbd3.png)
![image](https://cloud.githubusercontent.com/assets/51059/17025387/8dffbb1a-4f29-11e6-99f2-dbd74cf5a917.png)

**Comment by beruic** [comment] 2016-07-21 14:43
I just ran into this issue. Cannot tun `manage.py` commands correctly because I cannot load my environment file under Languages & Frameworks > Django.

**Comment by ashald** [comment] 2016-07-27 03:08
Can you please explain how do I get to the window that doesn't have env file component?

**Comment by cancan101** [comment] 2016-07-27 03:46
I am using Pycharm Pro:
![image](https://cloud.githubusercontent.com/assets/51059/17163223/0d9d066a-538b-11e6-9cf4-1597e6519352.png)

**Comment by beruic** [comment] 2016-07-28 09:36
I should mention that I have switched to using [Django-environ](https://github.com/joke2k/django-environ/) instead. It works very well (although the documentation could be better), and is IDE independent.

**Comment by ashald** [comment] 2017-01-17 01:17
This is not feasible to implement considering current design of the plugin so it won't be included in v2.0 but may be added in future. Stay tuned.

**Comment by ashald** [comment] 2017-01-22 23:27
The biggest problem with Django support in PyCharm is that it's part of the "ultimate" edition and therefore there are no source code available for any components involved. It appears that `EnvFile` version `1.x.x` was partially compatible with it due to a mere coincidence (I was doing dirty patching in order to integrate the plugin with UI).
Since version `2.0` was released it appears that there is no way to use the plugin with any of components designed for integration with Django. While I understand how Django is popular among PyCharm community at the moment I don't see a feasible way to integrate `EnvFile` with it. I'm going to close the issue for now but I'll keep an eye on further PyCharm updates with the hope that we will get a way for integration in future.

**Closed by ashald** 2017-01-22 23:27 UTC
Labels: enhancement

**Comment by drdaeman** [comment] 2017-01-23 10:08
Sorry to bump, but does this apply to "Build, Execution, Deployment > Console > Python Console" as well? (Or should I create another issue for this?)

I'm on professional edition, but I believe plain (non-Django) Python console is a part of community edition. EnvFile used to work there as well, now it's gone.

**Comment by ashald** [comment] 2017-02-02 02:53
Yeah, unfortunately, that's not going to work. Previously EnvFile plugin was injecting its UI components into so-called `PyCommonOptions` panel. It's widely used in PyCharm and that's the reason why we saw the plugin in many places. Unfortunately, such approach involved some "hacking" which wasn't super stable and absolutely not compatible with other platforms. The new version integrates in a more proper way via `RunConfigurationExtension`s which is supported across many JetBrains platforms. I understand that some people going to miss `EnvFile` plugin functionality in such places as `Django Console` and `Python Console` and I'd hope to figure out to bring EnvFile back to those places but so far I haven't discovered a feasible way to do so.
